version: '3.6'

services:
  userstorage.webapi:
    image: userstorage
    build:
      context: .
      dockerfile: UserStorage.WebApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql
    hostname: mssql
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Rpassw!1
    ports:
      - "1443:1433"
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=mysecretpassword